version: '3.8'

services:
  web:
    build: ./web
    container_name: web
    hostname: web
    ports:
      - "8100:80"
    volumes:
      - ../app:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: instituto
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8101:80"
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    depends_on:
      - mysql

volumes:
  mysql_data:
